### ISSUE TITLE
ESME: session getting messed up after GenServer.call timeout

### ISSUE THREAD

**Issue by archSeer** [savonarola/smppex#26]
Sadly I can't provide many details for this as we ran out of disk space for logs this weekend and I'm missing the logs from when this started, but:

We have a pool of ESMEs through which we send messages out. For some reason, after about 2-3 days of running without restarts, we started getting failures on most (maybe all?) of the processes. The weird thing is, each process started to get enquire_link_timer failures, but not just once, but hundreds of times over the next ~18 seconds, after which it seems to finally get killed (and we restart it):

```
# basically this, spanning 500 lines
time=20:15:19.904 level=info esme #PID<0.8869.0>, being stopped by timers(enquire_link_timer)
# ...
time=20:15:32.876 level=info	esme #PID<0.8869.0>, being stopped by timers(enquire_link_timer)
time=20:15:32.913 level=info	service=esme_consumer action=route to=Provider pid=#PID<0.8869.0> uuid=11111-2222-333-4444-555555
time=20:15:32.987 level=info	esme #PID<0.8869.0>, being stopped by timers(enquire_link_timer)
time=20:15:33.078 level=info	esme #PID<0.8869.0>, being stopped by timers(enquire_link_timer)
time=20:15:33.179 level=info esme #PID<0.8869.0>, being stopped by timers(enquire_link_timer)
# ...
time=20:15:37.224 level=info	esme #PID<0.8869.0>, being stopped by timers(enquire_link_timer)
time=20:15:37.320 level=info	esme #PID<0.8869.0>, being stopped by timers(enquire_link_timer)
time=20:15:37.421 level=info	esme #PID<0.8869.0>, being stopped by timers(enquire_link_timer)
time=20:15:37.522 level=info	esme #PID<0.8869.0>, being stopped by timers(enquire_link_timer)
time=20:15:37.623 level=info	esme #PID<0.8869.0>, being stopped by timers(enquire_link_timer)
time=20:15:37.724 level=info	esme #PID<0.8869.0>, being stopped by timers(enquire_link_timer)
time=20:15:37.815 level=error GenServer #PID<0.8869.0> terminating
``` 

However, this doesn't seem like a normal enquire_link timeout, because anything else that was using timers (`st.time`) would also go crazy. Any pdu message we would try to send would immediately (~5-100ms later) time out (`handle_resp_timeout`), even though we had `response_limit` set to 20_000.

```
SMPPEX.ESME.start_link(host, port, {__MODULE__, opts}, [esme_opts: [enquire_link_limit: 45_000, response_limit: 20_000]])

```

```
time=20:15:22.392 level=info	service=esme_consumer action=route to=Provider pid=#PID<0.8936.0> uuid=11111-2222-333-4444-555555
time=20:15:22.403 level=error	bound=true bind_type=transceiver carrier=Provider service=esme op=submit_sm_resp status=error uuid=11111-2222-333-4444-555555 reason=timeout
``` 

We do trap exits inside the ESME, but since it's a GenServer, I think all it does is it ensures that subprocess exits are caught, and if the process gets an exit signal, terminate/2 gets called for us for graceful shutdown.

It so far only happened once, but when it did, it seemed to continue happening continually, even after processes restarted. We restarted the entire node and it got back to normal. Everything seems to stem from that `st.time` which is updated every tick. Highly unlikely, but could this be a monotonic timer bug? It's possible it could be a bug in our application code too, but that doesn't explain why the timeout would be happening so fast (~5-100ms instead of 20s).

We're currently looking into this urgently because the timeouts start happening so fast, before the actual response has time to return, so we've been delivering duplicate messages

**Comment by archSeer** [comment]
@savonarola Ok so I got it replicated with a minimum repro case!

What happens is, if a handle_pdu/handle_resp takes longer than 5s (GenServer timeout), the ranch connection will somehow break. When that happens, `enquire_link` will eventually fail to send, time out, then our bug is triggered.


```
00:16:49.911 [info]  Starting ESME localhost:2775 as `archseer`
Bound!

00:16:55.352 [error] GenServer #PID<0.547.0> terminating
** (stop) exited in: GenServer.call(#PID<0.543.0>, {:handle_pdu, %SMPPEX.Pdu{command_id: 2147483657, command_status: 0, mandatory: %{system_id: "my_system"}, optional: %{}, ref: #Reference<0.0.5.565>, sequence_number: 1}}, 5000)
    ** (EXIT) time out
    (elixir) lib/gen_server.ex:737: GenServer.call/3
    (smppex) lib/smppex/esme/smpp_handler.ex:29: SMPPEX.SMPPHandler.SMPPEX.ESME.SMPPHandler.handle_pdu/2
    (smppex) lib/smppex/session.ex:129: SMPPEX.Session.handle_parse_result/3
    (stdlib) gen_server.erl:601: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:667: :gen_server.handle_msg/5
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
Last message: {:tcp, #Port<0.12402>, <<0, 0, 0, 23, 128, 0, 0, 9, 0, 0, 0, 0, 0, 0, 0, 1, 110, 105, 109, 98, 117, 115, 0>>}
State: %{buffer: "", ref: #Reference<0.0.5.529>, session: %SMPPEX.ESME.SMPPHandler{esme: #PID<0.543.0>}, socket: #Port<0.12402>, transport: :ranch_tcp}

00:16:55.360 [error] Ranch listener #Reference<0.0.5.529> had connection process started with SMPPEX.Session:start_link/4 at #PID<0.547.0> exit with reason: {:timeout, {GenServer, :call, [#PID<0.543.0>, {:handle_pdu, %SMPPEX.Pdu{command_id: 2147483657, command_status: 0, mandatory: %{system_id: "my_system"}, optional: %{}, ref: #Reference<0.0.5.565>, sequence_number: 1}}, 5000]}}


00:17:35.316 [info]  esme #PID<0.543.0>, being stopped by timers(enquire_link_timer)

00:17:35.417 [info]  esme #PID<0.543.0>, being stopped by timers(enquire_link_timer)

00:17:35.518 [info]  esme #PID<0.543.0>, being stopped by timers(enquire_link_timer)

00:17:35.619 [info]  esme #PID<0.543.0>, being stopped by timers(enquire_link_timer)

00:17:35.720 [info]  esme #PID<0.543.0>, being stopped by timers(enquire_link_timer)

00:17:35.821 [info]  esme #PID<0.543.0>, being stopped by timers(enquire_link_timer)
```

Here's the mix task used to replicate it (it will bind, then we will sleep 6s after receiving bind_resp, about a minute later the enquire_link will fail and then enquire_link will fail every 100ms):

```elixir
defmodule Mix.Tasks.EchoEsme do
  use Mix.Task

  defmodule Client do
    @moduledoc """
    Test client, should be able to receive stuff.
    """

    use SMPPEX.ESME
    alias SMPPEX.Pdu

    require Logger

    def start_link(%{host: host, port: port} = opts) do
      Logger.info "Starting ESME #{host}:#{port} as `#{opts[:system_id]}`"
      SMPPEX.ESME.start_link(host, port, {__MODULE__, opts}, [esme_opts: [enquire_link_limit: 15_000]])
    end

    def init(%{system_id: system_id, password: password} = opts) do
      SMPPEX.ESME.send_pdu(self(), Pdu.Factory.bind_transceiver(system_id, password))
      {:ok, opts}
    end

    def handle_pdu(pdu, st) do
      case pdu |> Pdu.command_id |> SMPPEX.Protocol.CommandNames.name_by_id do
        {:ok, :deliver_sm} ->
          IO.puts "Received a message!"
          IO.inspect pdu
          SMPPEX.ESME.reply(self(), pdu, Pdu.Factory.deliver_sm_resp)
          st
        {:ok, :enquire_link} ->
          SMPPEX.ESME.reply(self(), pdu, Pdu.Factory.enquire_link_resp)
          st
        _ ->
          IO.inspect pdu
          st
      end
    end

    def handle_resp(pdu, _original_pdu, st) do
      case pdu |> Pdu.command_id |> SMPPEX.Protocol.CommandNames.name_by_id do
        {:ok, :submit_sm_resp} ->
          st
        {:ok, :bind_transceiver_resp} ->
          if SMPPEX.Pdu.success_resp?(pdu) do
            IO.puts "Bound!"
            SMPPEX.ESME.send_pdu(self(), Pdu.Factory.enquire_link)
          else
            IO.puts "Failed to bind."
            IO.inspect pdu
          end
          Process.sleep(6000)
          st
        {:ok, :enquire_link_resp} ->
          IO.puts "GOT ENQUIRE LINK RESP"
          IO.inspect pdu
        _ ->
          st
      end
    end

    def handle_resp_timeout(pdu, st) do
      Logger.error("PDU timeout: #{inspect pdu}, terminating")
      # SMPPEX.ESME.stop(self())
      st
    end

    def handle_stop(reason, _lost, st) do
      Logger.info("ESME stopped: #{reason}")
      st
    end

    def handle_cast({:send, %Pdu{} = pdu}, state) do
      SMPPEX.ESME.send_pdu(self(), pdu)
      state
    end
  end

  def run(_) do
    Application.ensure_all_started(:smppex)
    Client.start_link(%{host: "localhost", port: 2775, system_id: "archseer", password: "test"})
    Process.sleep(:infinity)
  end

end

```

**Comment by savonarola** [comment]
Hello!

Thanks a lot for the example. Seems that the bug here is that the whole ESME does not crash when its session  crashes.

**Comment by archSeer** [comment]
We just had this reoccur in production even with the 071801f fix :/ stay tuned, doing a bit more looking into this in the morning

**Comment by savonarola** [comment]
Wow

**Comment by archSeer** [comment]
Seems to be the same issue, but the error messages are different than in the test case I gave.

What seems to still happen is, SMPPEX.Session tries to send a message to ESME, but the call times out and the Session dies. For some reason, ESME still keeps running:

```
time=20:44:36.101 level=error	GenServer #PID<0.6017.0> terminating
time=20:44:36.102 level=error	Ranch protocol #PID<0.6017.0> (SMPPEX.Session) of listener #Reference<0.0.3407873.99573> terminated
# ...
** (exit) exited in: GenServer.call(#PID<0.6015.0>, {:handle_pdu, %SMPPEX.Pdu{command_id: 5, command_status: 0, mandatory: %{...}, optional: %{}, ref: #Reference<0.0.3670017.180829>, sequence_number: 743084081}}, 5000)
	    ** (EXIT) time out
# ...

```

**Comment by archSeer** [comment]
Ok so what caused it was we were trapping exits inside the esme and ignoring things in handle_info (SMPPEX only takes state as the return value so we couldn't properly stop it there)
